name: Cleanup runner caches 

on:
  workflow_dispatch: 
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Cleanup all caches
        run: |
          echo "Fetching list of all cache keys"
          cacheKeys=$(gh cache list --limit 1000 --json id --jq '.[].id')

          ## Prevent failure if a delete fails
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              echo "Deleting cache $cacheKey"
              gh cache delete $cacheKey
          done
          echo "Done"

        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
